### ISSUE TITLE
Virtual Robot RR its outdated 

### ISSUE THREAD

**Issue by shaunsingh** [Beta8397/virtual_robot_rr#1]
Hello. This is Shaurya from team 10669, and at the moment since our team is virtual, we have to rely on virtual robot simulator to test out code. However, a bit of our code utilizes road runner, and this project is quite outdated. Is there any way to merge the two branches (virtual robot and virtual robot rr) or update this to match the other simulator?

Sincerely, 
Shaurya

**Comment by jkenney2** [comment]
@shaunsingh Shouldn't be too difficult. I'll try to do that today, and push the merged version back up to virtual_robot_rr. You should then be able to either add your teamcode to the updated version, or merge the updated version into your version.

**Comment by jkenney2** [comment]
@shaunsingh    I've pushed a new branch, "merge_upstream", that incorporates the changes to virtual_robot. But in testing, there is a bug where sometimes the app hangs when you try to re-run an op mode that ran fine the first time. It seems to involve iterative  (e.g., DriveSplineRegular) rather than linear op modes. It seems to happen with the Encoder Bot config but not the Mechanum Bot config. Just adding "System.out.println" statements for debugging seems to fix it, so I think it is a synchronization problem, but haven't sorted it out yet. I think it is a previously-uncovered bug in virtual_robot. Regardless, it will probably work for you.

**Comment by shaunsingh** [comment]
Thank you for all the help!

**Comment by jkenney2** [comment]
Bug fixed (I think), and merge_upstream branch to be merged onto master.
